# 📝 Based on: `5_builderprecompiled_base-dev-environment.yml`
#
# 📦 Manual Build Workflow for Wazuh Dashboard Reporting Plugin
#
# ⚡ Overview:
# This workflow builds and tests production-ready packages for Wazuh Dashboard Reporting plugin,
# either manually or triggered by other workflows.
#
# 🚀 Key Features:
# - 🖇️ Manual or Automated Builds: Supports manual execution or invocation from other workflows,
#   specifying any valid code reference (branch, tag, or commit SHA).
# - 🏗️ Production-Ready Package Generation: Builds a production-ready package from the provided code reference.
# - 🌐 Reusable Build Environment: Reuses a preconfigured build environment, ensuring consistency and easier maintenance.
#

name: Manual build

on:
  workflow_call:
    inputs:
      reference:
        required: true
        type: string
        description: Source code reference (branch, tag or commit SHA)
        default: 4.10.0
  workflow_dispatch:
    inputs:
      reference:
        required: true
        type: string
        default: main
        description: Source code reference (branch, tag or commit SHA)

jobs:
  # Build an app package from the given source code reference.
  build:
    name: Build app package
    uses: ./.github/workflows/5_builderprecompiled_base-dev-environment.yml
    with:
      reference: ${{ inputs.reference }}
      command: 'yarn build'
      artifact_name: 'reports-dashboards'
      artifact_path: './wazuh-dashboards-reporting/build'
    secrets: inherit
